version: 0.0
os: linux
files:
  - source: /messenger/build/
    destination: /
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: /scripts/validate_service.sh
      timeout: 300