version: 0.2
phases:
  install:
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - chmod +x ./scripts/create_vars.sh
      - ./scripts/create_vars.sh
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - aws s3 rm s3://v1-messenger-app --recursive
      - aws s3 cp --recursive --acl public-read ./messenger/build s3://v1-messenger-app/
artifacts:
  files:
    - '**/*'
  name: deploy-cicd-build-artifacts